### ISSUE TITLE
0.0 [2] - I want to be able to create a new account

### ISSUE THREAD

**Issue by KZhang2002** [KZhang2002/webRepo#3]

**Comment by preston-willis** [comment]
![Login](https://user-images.githubusercontent.com/24803045/228424350-e320a7c1-a7a0-46ff-b706-2971cb743e7d.PNG)
![Signup](https://user-images.githubusercontent.com/24803045/228424359-402fa997-cfe3-4949-9ef6-46f02fc08350.PNG)
Basic UI Mockup

**Comment by sithsiri** [comment]
Database completed: POST /user endpoint
